# Generated by Django 3.2.3 on 2021-05-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routList', '0002_rename_rating_rout_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rout',
            name='attempts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rout',
            name='date_climbed',
            field=models.DateField(blank=True),
        ),
    ]
