# Generated by Django 3.2.3 on 2021-05-24 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routList', '0006_rout_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rout',
            name='climber',
        ),
    ]
